title: SQL Pro Insights
description: Practical Technology. Real-World Solutions.
url: "https://sqlproinsights.com"

logo: /assets/images/favicon.svg

social:
  name: SQL Pro Insights
  links:
    - https://sqlproinsights.github.io/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/social-preview.png
      
author:
  name: Pramod Kumar Singh

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

permalink: /blog/:title/
exclude:
  - templates
