title: SQL Pro Insights
description: Practical Technology. Real-World Solutions.
url: "https://sqlproinsights.github.io"

author:
  name: Pramod Kumar Singh

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

permalink: /blog/:title/
exclude:
  - templates
